spring:
  application:
    name: api
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
server:
  port: 8080
  servlet:
    context-path: /api/v1
logging:
  level:
    root: INFO                      # default level
    org.springframework: INFO        # Spring framework logs
    org.hibernate.SQL: WARN          # Hibernate SQL logs (if used)
    org.zalando.logbook: TRACE

logbook:
  format:
    style: json
  predicate:
    exclude:
      - path: /actuator/**
      - path: /swagger-ui/**
      - path: /v3/api-docs/**
  obfuscate:
    headers:
      - Authorization
      - Cookie
      - Set-Cookie
      - X-API-KEY
      - Proxy-Authorization
    parameters:
      - password
      - access_token
      - refresh_token
      - token
      - client_secret
      - secret
    json-body-fields:
      - password
      - currentPassword
      - newPassword
      - accessToken
      - refreshToken
      - token
      - secret
jwt:
  secret: supergigamegasecretkeyforsureforrealforreal9
  expiration: 7200000          # 2 hours in ms
  refresh-expiration: 2592000000   # 30 days in ms
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
